---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  bazel_arch:
    name: bazel arch latest
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: pre-checkout setup
        run: |
          pacman --noconfirm -S -u -y
          pacman --noconfirm -S \
            ca-certificates \
            git
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          pacman --noconfirm -S -y \
            bazel \
            gcc \
            python \
            which
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: build test package
        run: bazel test ...
        shell: bash

  bazel_macos:
    name: bazel macos latest
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: |
          rm -f /usr/local/bin/2to3
          brew unlink gcc@8
          brew unlink gcc@9
          brew update
          brew uninstall -q bazelisk
          brew bundle install --no-lock
        shell: zsh -efuo pipefail {0}
      - name: build test package
        run: bazel test ...
        shell: zsh -efuo pipefail {0}

  bazel_ubuntu:
    name: bazel ubuntu latest
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: pre-checkout setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            g++ \
            gnupg \
            python-is-python3
          export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
          apt-key adv -q --fetch-keys https://bazel.build/bazel-release.pub.gpg
          echo 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8' \
            > /etc/apt/sources.list.d/bazel.list
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends bazel
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: build test package
        run: bazel test ...
        shell: bash

  cmake_alpine:
    name: cmake alpine latest
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: pre-checkout setup
        run: |
          apk add --no-cache \
            ca-certificates \
            git
        shell: sh
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          apk add --no-cache \
            cmake \
            doxygen \
            g++ \
            graphviz \
            make \
            pkgconf
        shell: sh
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=ON \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DWARNINGS_AS_ERRORS:BOOL=ON \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
          cpack -G TGZ
          cpack -G TGZ --config CPackSourceConfig.cmake
        shell: sh

  cmake_arch:
    name: cmake arch latest
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: pre-checkout setup
        run: |
          pacman --noconfirm -S -u -y
          pacman --noconfirm -S \
            ca-certificates \
            git
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          pacman --noconfirm -S -y \
            cmake \
            doxygen \
            gcc \
            graphviz \
            make \
            pkgconf
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=ON \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DWARNINGS_AS_ERRORS:BOOL=ON \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
          cpack -G TGZ
          cpack -G TGZ --config CPackSourceConfig.cmake
        shell: bash

  cmake_centos:
    name: cmake centos latest
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: pre-checkout setup
        run: |
          dnf install -q -y \
            ca-certificates \
            glibc-langpack-en \
            git
          dnf clean all
          rm -rf /var/cache/yum
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          dnf install -q -y \
            cmake \
            dnf-plugins-core \
            gcc-c++ \
            graphviz \
            make \
            pkgconf-pkg-config \
            redhat-lsb-core \
            rpm-build
          dnf config-manager --set-enabled powertools
          dnf install -q -y doxygen
          dnf clean all
          rm -rf /var/cache/yum
        shell: bash
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=ON \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DWARNINGS_AS_ERRORS:BOOL=ON \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
          cpack -G RPM
          cpack -G RPM --config CPackSourceConfig.cmake
        shell: bash

  cmake_macos:
    name: cmake macos latest
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: |
          rm -f /usr/local/bin/2to3
          brew unlink gcc@8
          brew unlink gcc@9
          brew update
          brew uninstall -q bazelisk
          brew bundle install --no-lock
        shell: zsh -efuo pipefail {0}
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=OFF \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DWARNINGS_AS_ERRORS:BOOL=ON \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
          cpack -G TGZ
          cpack -G TGZ --config CPackSourceConfig.cmake
        shell: zsh -efuo pipefail {0}

  cmake_ubuntu:
    name: cmake ubuntu latest
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: pre-checkout setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            doxygen \
            dpkg \
            dpkg-dev \
            file \
            g++ \
            gnupg \
            graphviz \
            lsb-release \
            make \
            pkg-config
          export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
          apt-key adv -q --fetch-keys \
            https://apt.kitware.com/keys/kitware-archive-latest.asc
          echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
            > /etc/apt/sources.list.d/kitware.list
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends cmake
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=ON \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DWARNINGS_AS_ERRORS:BOOL=ON \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
          cpack -G DEB
          cpack -G DEB --config CPackSourceConfig.cmake
        shell: bash

  cmake_windows:
    name: cmake windows latest
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: |
          cup cmake.install -r -y --install-arguments=ADD_CMAKE_TO_PATH=System `
            --no-progress
          cinst doxygen.install -f -r -y
        shell: powershell
      - name: build test package
        run: |
          mkdir _build
          cd _build
          cmake `
            -DBUILD_DOCUMENTATION:BOOL=ON `
            -DBUILD_TESTING:BOOL=ON `
            -DCMAKE_INSTALL_PREFIX:PATH=install `
            -DENABLE_HARDENING:BOOL=ON `
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON `
            -DENABLE_OPENMP:BOOL=OFF `
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF `
            -DWARNINGS_AS_ERRORS:BOOL=ON `
            --warn-uninitialized `
            ..
          cmake --build . --config Release
          ctest . --build-config Release
          cmake --install .
          cpack -C Release -G ZIP
          cpack -C Release -G ZIP --config CPackSourceConfig.cmake
        shell: powershell
